GET http://localhost:3000/users

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "gmhammer99@gmail.com",
    "password": "joe123"
}

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "yousef",
    "email": "gmhammer99@gmail.com",
    "password": "joe123"
}